### PR TITLE
Add custom 404 pages (DE, EN)

### PR DESCRIPTION
**Pull request by raphaelschaad**
This addresses issue #10. The content of the pages is a simple message and a "back to home" link. The content can get more creative over time.

Configure Netlify to serve these custom 404 pages for all requested URLs that don't match any existing static files or other redirects.

localhost_8000_404 html

### CODE REVIEW

**Comment by raphaelschaad** [comment]
Tested and self-reviewed. Merging.

**Comment by xaverfleer** [comment]
LGTM

**Comment by raphaelschaad** [comment]
I don't seem to be able to see what commit you're referring to. If I'm not mistaken, you've just commented on the entire PR.

**Comment by xaverfleer** [comment]
you are right!

**Comment by raphaelschaad** [comment]
Sooo ...? What commit *are* you referring to?

**Comment by xaverfleer** [comment]
I am referring to the entire PR

**Comment by raphaelschaad** [comment]
Moving discussion to Slack.

**Pull request merged**
