### PR TITLE
chore/submission-created-payload

### PR DESCRIPTION
**Pull request by raphaelschaad**
This is a minor code change on the server motivated by some client-side work. Done in a separate PR so could test end-to-end using Netlify's deploy preview feature.

### CODE REVIEW

**Comment by xaverfleer** [comment]
For my understanding: Did you also change `body.payload.human_fields` to `body.payload.data` on Netlify's web app?

**Comment by xaverfleer** [comment]
Besides: LGTM

**Comment by raphaelschaad** [comment]
Yes, in a later commit, inspired by actually looking at the full payload obj doing some front end work. The `human_fields` approach is something I originally got from a tutorial, I believe. But I think using the data field (although populated w/ exactly the same values) is the semantically more correct approach. I'm actually not sure why they include `human_fields` in the first place.

**Comment by raphaelschaad** [comment]
No. Inspired by actually looking more carefully at the full payload obj doing some front end work, I found that both fields are populated w/ exactly the same values. I'm actually not sure what the exact intention for `human_fields` is. I believe I originally got that from a third party tutorial. But I think using the `data` field is the semantically more correct approach.

**Pull request merged**
